### ISSUE TITLE
about css

### ISSUE THREAD

**Issue by ghost** [ozgrozer/dasper#6]
Hello, how to modify CSS, dev and prov should modify which one, the other can be deleted or not?

**Comment by ozgrozer** [comment]
Since this project is old, it uses [Gulp](https://gulpjs.com/) to parse and compress [SCSS](./../blob/master/gulpfile.js#L13) files. When you edit files inside of the [`/assets/css/dev/`](./../tree/master/assets/css/dev) folder, Gulp will export the minified versions of them to the [`/assets/css/prod/`](./../tree/master/assets/css/prod/) folder. And [`/_layouts/default.html`](./../tree/master/_layouts/default.html#L64) uses the minified versions.
